In [ ]:
#librosa is library used to read audio files for python

# with librosa we convert song into number => signal, sr = librosa.load(file_path, sr=22050)
# sr means sample rate => 22050 values every second
# This list is called
# Signal (Waveform)
# Every number represents the loudness of the sound at one instant.

# A 30-second song contains
# intro
# chorus
# guitar solo
# ending
# Different parts sound different.
# Instead of learning one huge song,
# we split it.
# 30 seconds => 3 sec+ 3 sec + .....
# This is called
# Segmentation

# For music,
# we describe
# Brightness
# Rhythm
# Melody
# Timbre
# These descriptions are called
# Audio Features

# 1. MFCC (Mel-Frequency Cepstral Coefficients) ✅
# "What does this sound like?"
# It captures the texture (timbre) of the sound.
# For example:
# 🎸 Guitar
# 🎹 Piano
# 🎺 Trumpet
# 🎤 Human voice
# Even if they play the same note, they sound different.
# MFCC captures that difference.
# 13 output for each segment

# 2. Chroma Features ✅
# "Which musical notes are being played?"
# Instead of instrument, it focuses on music notes.
# Western music has only 12 note classes:
# C
# C#
# D
# D#
# E
# F
# F#
# G
# G#
# A
# A#
# B
# Chroma tells us how much of each note exists.

# 3. Spectral Centroid ✅
# "Is this sound bright or dark?"
# It measures where most of the sound energy lies.
# Low frequencies
# Bass
# Drums
# Deep voice => Dark sound
# High frequencies
# Cymbals
# Flute
# Hi-hats => Bright sound

# Song (.wav)
#         │
# Load using librosa
#         │
# Split into 10 segments
#         │
# For each segment
#         │
#         ├── MFCC
#         │      → Sound texture (instrument/timbre)
#         │
#         ├── Chroma
#         │      → Musical notes & chords
#         │
#         └── Spectral Centroid
#                → Brightness of sound

# | Feature               | Easy way to remember                                         |
# | --------------------- | ------------------------------------------------------------ |
# | **MFCC**              | Instrument or sound texture                                  |
# | **Chroma**            | Musical notes/chords                                         |
# | **Spectral Centroid** | Average brightness (center of frequencies)                   |
# | **Spectral Rolloff**  | Frequency below which **85% of the sound energy** is present |
# | **zero crossing rate**| smoothness of song less zcr more smooth                      |

In [ ]:
import os
import json
import librosa

# Dataset path
DATASET_PATH = "archive/Data/genres_original"

# Output JSON file
JSON_PATH = "data.json"

# Audio processing constants
SAMPLE_RATE = 22050
TRACK_DURATION_SECONDS = 30
NUM_SEGMENTS = 10

# Samples in one track
SAMPLES_PER_TRACK = SAMPLE_RATE * TRACK_DURATION_SECONDS


def process_dataset(dataset_path, json_path):
    """
    Process the dataset and extract audio features.
    """

    data = {
        "mapping": [],
        "labels": [],
        "features": []
    }

    print("Starting feature extraction...")
    print("Feature extraction complete.")


if __name__ == "__main__":
    process_dataset(DATASET_PATH, JSON_PATH)

In [ ]:
import os
import json
import librosa

# Dataset path
DATASET_PATH = "archive/Data/genres_original"

# Output JSON file
JSON_PATH = "data.json"

# Audio processing constants
SAMPLE_RATE = 22050
TRACK_DURATION_SECONDS = 30
NUM_SEGMENTS = 10

# Samples in one track
SAMPLES_PER_TRACK = SAMPLE_RATE * TRACK_DURATION_SECONDS


def process_dataset(dataset_path, json_path):
    """
    Process the dataset and extract features.
    """

    data = {
        "mapping": [],
        "labels": [],
        "features": []
    }

    print("Starting feature extraction...\n")

    # Loop through each genre folder
    for i, (dirpath, dirnames, filenames) in enumerate(os.walk(dataset_path)):

        # Skip the root dataset folder
        if dirpath == dataset_path:
            continue

        # Get genre name
        genre = os.path.basename(dirpath)

        print(f"Processing genre: {genre}")

        # Store genre mapping
        data["mapping"].append(genre)

    print("\nFeature extraction complete.")

if __name__ == "__main__":
    process_dataset(DATASET_PATH, JSON_PATH)

In [ ]:
import os
import json
import librosa

# Dataset path
DATASET_PATH = "archive/Data/genres_original"

# Output JSON file
JSON_PATH = "data.json"

# Audio processing constants
SAMPLE_RATE = 22050
TRACK_DURATION_SECONDS = 30
NUM_SEGMENTS = 10

# Samples in one track
SAMPLES_PER_TRACK = SAMPLE_RATE * TRACK_DURATION_SECONDS


def process_dataset(dataset_path, json_path):

    data = {
        "mapping": [],
        "labels": [],
        "features": []
    }

    print("Starting feature extraction...\n")

    for i, (dirpath, dirnames, filenames) in enumerate(os.walk(dataset_path)):

        if dirpath == dataset_path:
            continue

        genre = os.path.basename(dirpath)

        print(f"\nProcessing genre: {genre}")

        data["mapping"].append(genre)

        # Loop through every audio file
        for filename in filenames:
            if filename.endswith(".wav"):
        
                file_path = os.path.join(dirpath, filename)
        
                try:
                    signal, sr = librosa.load(file_path, sr=SAMPLE_RATE)
        
                except Exception as e:
                    print(f"Error loading file {file_path}: {e}")
                    continue

    print("\nFeature extraction complete.")

if __name__ == "__main__":
    process_dataset(DATASET_PATH, JSON_PATH)

In [ ]:
import os
import json
import librosa
import numpy as np

# Dataset path
DATASET_PATH = "archive/Data/genres_original"

# Output JSON file
JSON_PATH = "data.json"

# MFCC constants
NUM_MFCC = 13
N_FFT = 2048
HOP_LENGTH = 512

# Audio processing constants
SAMPLE_RATE = 22050
TRACK_DURATION_SECONDS = 30
NUM_SEGMENTS = 10

# Samples in one track
SAMPLES_PER_TRACK = SAMPLE_RATE * TRACK_DURATION_SECONDS
# Samples in each segment
NUM_SAMPLES_PER_SEGMENT = SAMPLES_PER_TRACK // NUM_SEGMENTS

def process_dataset(dataset_path, json_path):

    data = {
        "mapping": [],
        "labels": [],
        "features": []
    }

    print("Starting feature extraction...\n")

    for i, (dirpath, dirnames, filenames) in enumerate(os.walk(dataset_path)):

        if dirpath == dataset_path:
            continue

        genre = os.path.basename(dirpath)

        print(f"\nProcessing genre: {genre}")

        data["mapping"].append(genre)

        # Loop through every audio file
        for filename in filenames:
            if filename.endswith(".wav"):
        
                file_path = os.path.join(dirpath, filename)
        
                try:
                    # Load audio
                    signal, sr = librosa.load(file_path, sr=SAMPLE_RATE)
                
                    # Check signal length
                    if len(signal) >= SAMPLES_PER_TRACK:
                
                        # Divide the signal into segments
                        for s in range(NUM_SEGMENTS):

                            start_sample = s * NUM_SAMPLES_PER_SEGMENT
                            end_sample = start_sample + NUM_SAMPLES_PER_SEGMENT
                        
                            segment = signal[start_sample:end_sample]
                            
                            # Extract MFCCs
                            mfccs = librosa.feature.mfcc(
                                y=segment,
                                sr=sr,
                                n_mfcc=NUM_MFCC,
                                n_fft=N_FFT,
                                hop_length=HOP_LENGTH
                            )
                            
                            # Take the mean of each MFCC coefficient
                            mfccs_processed = np.mean(mfccs, axis=1)
                            
                            # Optional: print shape for verification
                            # print(mfccs_processed.shape)
                
                            # Optional: print for verification
                            # print(f"{filename} -> Segment {s+1}: {segment.shape}")

                            
                            # Extract Chroma Features
                            chroma = librosa.feature.chroma_stft(
                                y=segment,
                                sr=sr,
                                n_fft=N_FFT,
                                hop_length=HOP_LENGTH
                            )

                            # Average the chroma values across time
                            chroma_processed = np.mean(chroma, axis=1)
                            
                            # Optional: verify shape
                            # print(chroma_processed.shape)
                
                except Exception as e:
                    print(f"Error loading file {file_path}: {e}")
                    continue

    print("\nFeature extraction complete.")

if __name__ == "__main__":
    process_dataset(DATASET_PATH, JSON_PATH)

In [28]:
import os
import json
import librosa
import numpy as np

# Dataset Configuration

DATASET_PATH = "archive/Data/genres_original"

# Output JSON file
JSON_PATH = "data.json"

# Feature Extraction Constants

NUM_MFCC = 13

N_FFT = 2048
HOP_LENGTH = 512

SAMPLE_RATE = 22050

TRACK_DURATION_SECONDS = 30
NUM_SEGMENTS = 10


# Samples in complete track
SAMPLES_PER_TRACK = SAMPLE_RATE * TRACK_DURATION_SECONDS

# Samples in each 3-second segment
NUM_SAMPLES_PER_SEGMENT = SAMPLES_PER_TRACK // NUM_SEGMENTS

# Feature Extraction Function

def process_dataset(dataset_path, json_path):

    data = {
        "mapping": [],
        "labels": [],
        "features": []
    }


    print("\nStarting Feature Extraction...\n")


    # Loop through genres
    for i, genre in enumerate(sorted(os.listdir(dataset_path))):

        genre_path = os.path.join(dataset_path, genre)


        # Ignore non-folder files
        if not os.path.isdir(genre_path):
            continue


        print(f"Processing Genre: {genre}")


        # Store genre name
        data["mapping"].append(genre)



        # Loop through audio files
        for filename in os.listdir(genre_path):

            if filename.endswith(".wav"):


                file_path = os.path.join(
                    genre_path,
                    filename
                )


                try:

                    print(f"  Processing: {filename}")


                    # Load audio
                    signal, sr = librosa.load(
                        file_path,
                        sr=SAMPLE_RATE
                    )


                    # Check duration
                    if len(signal) < SAMPLES_PER_TRACK:
                        print("  Skipped (short file)")
                        continue

                    # Segment Extraction

                    for s in range(NUM_SEGMENTS):


                        start_sample = (
                            s * NUM_SAMPLES_PER_SEGMENT
                        )


                        end_sample = (
                            start_sample +
                            NUM_SAMPLES_PER_SEGMENT
                        )


                        segment = signal[
                            start_sample:end_sample
                        ]

                        # MFCC

                        mfccs = librosa.feature.mfcc(
                            y=segment,
                            sr=sr,
                            n_mfcc=NUM_MFCC,
                            n_fft=N_FFT,
                            hop_length=HOP_LENGTH
                        )


                        mfccs_processed = np.mean(
                            mfccs,
                            axis=1
                        )

                        # Chroma

                        chroma = librosa.feature.chroma_stft(
                            y=segment,
                            sr=sr,
                            n_fft=N_FFT,
                            hop_length=HOP_LENGTH
                        )


                        chroma_processed = np.mean(
                            chroma,
                            axis=1
                        )

                        # Spectral Centroid

                        spectral_centroid = librosa.feature.spectral_centroid(
                            y=segment,
                            sr=sr,
                            n_fft=N_FFT,
                            hop_length=HOP_LENGTH
                        )


                        spectral_centroid_processed = np.mean(
                            spectral_centroid
                        )

                        # Spectral Rolloff

                        spectral_rolloff = librosa.feature.spectral_rolloff(
                            y=segment,
                            sr=sr,
                            n_fft=N_FFT,
                            hop_length=HOP_LENGTH
                        )


                        spectral_rolloff_processed = np.mean(
                            spectral_rolloff
                        )

                        # Zero Crossing Rate

                        zcr = librosa.feature.zero_crossing_rate(
                            y=segment,
                            hop_length=HOP_LENGTH
                        )


                        zcr_processed = np.mean(zcr)

                        # Combine Features

                        feature_vector = np.hstack(
                            (
                                mfccs_processed,
                                chroma_processed,
                                spectral_centroid_processed,
                                spectral_rolloff_processed,
                                zcr_processed
                            )
                        )



                        # Save feature vector
                        data["features"].append(
                            feature_vector.tolist()
                        )


                        # Save genre label
                        data["labels"].append(i)



                except Exception as e:

                    print(
                        f"Error processing {file_path}: {e}"
                    )

                    continue

    # Save JSON

    with open(json_path, "w") as f:

        json.dump(
            data,
            f,
            indent=4
        )


    print("Feature Extraction Completed")


    print(
        "Total Feature Vectors:",
        len(data["features"])
    )


    print(
        "Total Labels:",
        len(data["labels"])
    )


    print(
        "Feature Vector Size:",
        len(data["features"][0])
    )


# Main Execution

if __name__ == "__main__":

    process_dataset(
        DATASET_PATH,
        JSON_PATH
    )

Starting Feature Extraction...

Processing Genre: blues
  Processing: blues.00000.wav
  Processing: blues.00001.wav
  Processing: blues.00002.wav
  Processing: blues.00003.wav
  Processing: blues.00004.wav
  Processing: blues.00005.wav
  Processing: blues.00006.wav
  Processing: blues.00007.wav
  Processing: blues.00008.wav
  Processing: blues.00009.wav
  Processing: blues.00010.wav
  Processing: blues.00011.wav
  Processing: blues.00012.wav
  Processing: blues.00013.wav
  Processing: blues.00014.wav
  Processing: blues.00015.wav
  Processing: blues.00016.wav
  Processing: blues.00017.wav
  Processing: blues.00018.wav
  Processing: blues.00019.wav
  Processing: blues.00020.wav
  Processing: blues.00021.wav
  Processing: blues.00022.wav
  Processing: blues.00023.wav
  Processing: blues.00024.wav
  Processing: blues.00025.wav
  Processing: blues.00026.wav
  Processing: blues.00027.wav
  Processing: blues.00028.wav
  Processing: blues.00029.wav
  Processing: blues.00030.wav
  Processing: blues.00031.wav
  Processing: blues.00032.wav
  Processing: blues.00033.wav
  Processing: blues.00034.wav
  Processing: blues.00035.wav
  Processing: blues.00036.wav
  Processing: blues.00037.wav
  Processing: blues.00038.wav
  Processing: blues.00039.wav
  Processing: blues.00040.wav
  Processing: blues.00041.wav
  Processing: blues.00042.wav
  Processing: blues.00043.wav
  Processing: blues.00044.wav
  Processing: blues.00045.wav
  Processing: blues.00046.wav
  Processing: blues.00047.wav
  Processing: blues.00048.wav
  Processing: blues.00049.wav
  Processing: blues.00050.wav
  Processing: blues.00051.wav
  Processing: blues.00052.wav
  Processing: blues.00053.wav
  Processing: blues.00054.wav
  Processing: blues.00055.wav
  Processing: blues.00056.wav
  Processing: blues.00057.wav
  Processing: blues.00058.wav
  Processing: blues.00059.wav
  Processing: blues.00060.wav
  Processing: blues.00061.wav
  Processing: blues.00062.wav
  Processing: blues.00063.wav
  Processing: blues.00064.wav
  Processing: blues.00065.wav
  Processing: blues.00066.wav
  Processing: blues.00067.wav
  Processing: blues.00068.wav
  Processing: blues.00069.wav
  Processing: blues.00070.wav
  Processing: blues.00071.wav
  Processing: blues.00072.wav
  Processing: blues.00073.wav
  Processing: blues.00074.wav
  Processing: blues.00075.wav
  Processing: blues.00076.wav
  Processing: blues.00077.wav
  Processing: blues.00078.wav
  Processing: blues.00079.wav
  Processing: blues.00080.wav
  Processing: blues.00081.wav
  Processing: blues.00082.wav
  Processing: blues.00083.wav
  Processing: blues.00084.wav
  Processing: blues.00085.wav
  Processing: blues.00086.wav
  Processing: blues.00087.wav
  Processing: blues.00088.wav
  Processing: blues.00089.wav
  Processing: blues.00090.wav
  Processing: blues.00091.wav
  Processing: blues.00092.wav
  Processing: blues.00093.wav
  Processing: blues.00094.wav
  Processing: blues.00095.wav
  Processing: blues.00096.wav
  Processing: blues.00097.wav
  Processing: blues.00098.wav
  Processing: blues.00099.wav
Processing Genre: classical
  Processing: classical.00000.wav
  Processing: classical.00001.wav
  Processing: classical.00002.wav
  Processing: classical.00003.wav
  Processing: classical.00004.wav
  Processing: classical.00005.wav
  Processing: classical.00006.wav
  Processing: classical.00007.wav
  Processing: classical.00008.wav
  Processing: classical.00009.wav
  Processing: classical.00010.wav
  Processing: classical.00011.wav
  Processing: classical.00012.wav
  Processing: classical.00013.wav
  Processing: classical.00014.wav
  Processing: classical.00015.wav
  Processing: classical.00016.wav
  Processing: classical.00017.wav
  Processing: classical.00018.wav
  Processing: classical.00019.wav
  Processing: classical.00020.wav
  Processing: classical.00021.wav
  Processing: classical.00022.wav
  Processing: classical.00023.wav
  Processing: classical.00024.wav
  Processing: classical.00025.wav
  Processing: classical.00026.wav
  Processing: classical.00027.wav
  Processing: classical.00028.wav
  Processing: classical.00029.wav
  Processing: classical.00030.wav
  Processing: classical.00031.wav
  Processing: classical.00032.wav
  Processing: classical.00033.wav
  Processing: classical.00034.wav
  Processing: classical.00035.wav
  Processing: classical.00036.wav
  Processing: classical.00037.wav
  Processing: classical.00038.wav
  Processing: classical.00039.wav
  Processing: classical.00040.wav
  Processing: classical.00041.wav
  Processing: classical.00042.wav
  Processing: classical.00043.wav
  Processing: classical.00044.wav
  Processing: classical.00045.wav
  Processing: classical.00046.wav
  Processing: classical.00047.wav
  Processing: classical.00048.wav
  Processing: classical.00049.wav
  Skipped (short file)
  Processing: classical.00050.wav
  Processing: classical.00051.wav
  Skipped (short file)
  Processing: classical.00052.wav
  Processing: classical.00053.wav
  Processing: classical.00054.wav
  Processing: classical.00055.wav
  Processing: classical.00056.wav
  Processing: classical.00057.wav
  Processing: classical.00058.wav
  Processing: classical.00059.wav
  Processing: classical.00060.wav
  Processing: classical.00061.wav
  Processing: classical.00062.wav
  Processing: classical.00063.wav
  Processing: classical.00064.wav
  Processing: classical.00065.wav
  Processing: classical.00066.wav
  Processing: classical.00067.wav
  Processing: classical.00068.wav
  Processing: classical.00069.wav
  Processing: classical.00070.wav
  Processing: classical.00071.wav
  Processing: classical.00072.wav
  Processing: classical.00073.wav
  Processing: classical.00074.wav
  Processing: classical.00075.wav
  Processing: classical.00076.wav
  Processing: classical.00077.wav
  Processing: classical.00078.wav
  Processing: classical.00079.wav
  Processing: classical.00080.wav
  Processing: classical.00081.wav
  Processing: classical.00082.wav
  Processing: classical.00083.wav
  Processing: classical.00084.wav
  Processing: classical.00085.wav
  Processing: classical.00086.wav
  Processing: classical.00087.wav
  Processing: classical.00088.wav
  Processing: classical.00089.wav
  Processing: classical.00090.wav
  Processing: classical.00091.wav
  Processing: classical.00092.wav
  Processing: classical.00093.wav
  Processing: classical.00094.wav
  Processing: classical.00095.wav
  Processing: classical.00096.wav
  Processing: classical.00097.wav
  Processing: classical.00098.wav
  Processing: classical.00099.wav
Processing Genre: country
  Processing: country.00000.wav
  Processing: country.00001.wav
  Processing: country.00002.wav
  Processing: country.00003.wav
  Skipped (short file)
  Processing: country.00004.wav
  Skipped (short file)
  Processing: country.00005.wav
  Processing: country.00006.wav
  Processing: country.00007.wav
  Skipped (short file)
  Processing: country.00008.wav
  Processing: country.00009.wav
  Processing: country.00010.wav
  Processing: country.00011.wav
  Processing: country.00012.wav
  Processing: country.00013.wav
  Processing: country.00014.wav
  Processing: country.00015.wav
  Processing: country.00016.wav
  Processing: country.00017.wav
  Processing: country.00018.wav
  Processing: country.00019.wav
  Processing: country.00020.wav
  Processing: country.00021.wav
  Processing: country.00022.wav
  Processing: country.00023.wav
  Processing: country.00024.wav
  Processing: country.00025.wav
  Processing: country.00026.wav
  Processing: country.00027.wav
  Processing: country.00028.wav
  Processing: country.00029.wav
  Processing: country.00030.wav
  Processing: country.00031.wav
  Processing: country.00032.wav
  Processing: country.00033.wav
  Processing: country.00034.wav
  Processing: country.00035.wav
  Processing: country.00036.wav
  Processing: country.00037.wav
  Processing: country.00038.wav
  Processing: country.00039.wav
  Processing: country.00040.wav
  Processing: country.00041.wav
  Processing: country.00042.wav
  Processing: country.00043.wav
  Processing: country.00044.wav
  Processing: country.00045.wav
  Processing: country.00046.wav
  Processing: country.00047.wav
  Processing: country.00048.wav
  Processing: country.00049.wav
  Processing: country.00050.wav
  Processing: country.00051.wav
  Processing: country.00052.wav
  Processing: country.00053.wav
  Processing: country.00054.wav
  Processing: country.00055.wav
  Processing: country.00056.wav
  Processing: country.00057.wav
  Processing: country.00058.wav
  Processing: country.00059.wav
  Processing: country.00060.wav
  Processing: country.00061.wav
  Processing: country.00062.wav
  Processing: country.00063.wav
  Processing: country.00064.wav
  Processing: country.00065.wav
  Processing: country.00066.wav
  Processing: country.00067.wav
  Processing: country.00068.wav
  Processing: country.00069.wav
  Processing: country.00070.wav
  Processing: country.00071.wav
  Processing: country.00072.wav
  Processing: country.00073.wav
  Processing: country.00074.wav
  Processing: country.00075.wav
  Processing: country.00076.wav
  Processing: country.00077.wav
  Processing: country.00078.wav
  Processing: country.00079.wav
  Processing: country.00080.wav
  Processing: country.00081.wav
  Processing: country.00082.wav
  Processing: country.00083.wav
  Processing: country.00084.wav
  Processing: country.00085.wav
  Processing: country.00086.wav
  Processing: country.00087.wav
  Processing: country.00088.wav
  Processing: country.00089.wav
  Processing: country.00090.wav
  Processing: country.00091.wav
  Processing: country.00092.wav
  Processing: country.00093.wav
  Processing: country.00094.wav
  Processing: country.00095.wav
  Processing: country.00096.wav
  Processing: country.00097.wav
  Processing: country.00098.wav
  Processing: country.00099.wav
Processing Genre: disco
  Processing: disco.00000.wav
  Processing: disco.00001.wav
  Processing: disco.00002.wav
  Processing: disco.00003.wav
  Processing: disco.00004.wav
  Processing: disco.00005.wav
  Processing: disco.00006.wav
  Processing: disco.00007.wav
  Processing: disco.00008.wav
  Processing: disco.00009.wav
  Processing: disco.00010.wav
  Processing: disco.00011.wav
  Processing: disco.00012.wav
  Processing: disco.00013.wav
  Processing: disco.00014.wav
  Skipped (short file)
  Processing: disco.00015.wav
  Processing: disco.00016.wav
  Processing: disco.00017.wav
  Processing: disco.00018.wav
  Processing: disco.00019.wav
  Processing: disco.00020.wav
  Processing: disco.00021.wav
  Processing: disco.00022.wav
  Processing: disco.00023.wav
  Processing: disco.00024.wav
  Processing: disco.00025.wav
  Processing: disco.00026.wav
  Processing: disco.00027.wav
  Processing: disco.00028.wav
  Processing: disco.00029.wav
  Processing: disco.00030.wav
  Processing: disco.00031.wav
  Processing: disco.00032.wav
  Processing: disco.00033.wav
  Processing: disco.00034.wav
  Processing: disco.00035.wav
  Processing: disco.00036.wav
  Processing: disco.00037.wav
  Processing: disco.00038.wav
  Processing: disco.00039.wav
  Processing: disco.00040.wav
  Processing: disco.00041.wav
  Processing: disco.00042.wav
  Processing: disco.00043.wav
  Processing: disco.00044.wav
  Processing: disco.00045.wav
  Processing: disco.00046.wav
  Processing: disco.00047.wav
  Processing: disco.00048.wav
  Processing: disco.00049.wav
  Processing: disco.00050.wav
  Processing: disco.00051.wav
  Processing: disco.00052.wav
  Processing: disco.00053.wav
  Processing: disco.00054.wav
  Processing: disco.00055.wav
  Processing: disco.00056.wav
  Processing: disco.00057.wav
  Processing: disco.00058.wav
  Processing: disco.00059.wav
  Processing: disco.00060.wav
  Processing: disco.00061.wav
  Processing: disco.00062.wav
  Processing: disco.00063.wav
  Processing: disco.00064.wav
  Processing: disco.00065.wav
  Processing: disco.00066.wav
  Processing: disco.00067.wav
  Processing: disco.00068.wav
  Processing: disco.00069.wav
  Processing: disco.00070.wav
  Processing: disco.00071.wav
  Processing: disco.00072.wav
  Processing: disco.00073.wav
  Processing: disco.00074.wav
  Processing: disco.00075.wav
  Processing: disco.00076.wav
  Processing: disco.00077.wav
  Processing: disco.00078.wav
  Processing: disco.00079.wav
  Processing: disco.00080.wav
  Processing: disco.00081.wav
  Processing: disco.00082.wav
  Processing: disco.00083.wav
  Processing: disco.00084.wav
  Processing: disco.00085.wav
  Processing: disco.00086.wav
  Processing: disco.00087.wav
  Processing: disco.00088.wav
  Processing: disco.00089.wav
  Processing: disco.00090.wav
  Processing: disco.00091.wav
  Processing: disco.00092.wav
  Processing: disco.00093.wav
  Processing: disco.00094.wav
  Processing: disco.00095.wav
  Processing: disco.00096.wav
  Processing: disco.00097.wav
  Processing: disco.00098.wav
  Processing: disco.00099.wav
Processing Genre: hiphop
  Processing: hiphop.00000.wav
  Processing: hiphop.00001.wav
  Processing: hiphop.00002.wav
  Processing: hiphop.00003.wav
  Processing: hiphop.00004.wav
  Processing: hiphop.00005.wav
  Processing: hiphop.00006.wav
  Processing: hiphop.00007.wav
  Processing: hiphop.00008.wav
  Processing: hiphop.00009.wav
  Processing: hiphop.00010.wav
  Processing: hiphop.00011.wav
  Processing: hiphop.00012.wav
  Processing: hiphop.00013.wav
  Processing: hiphop.00014.wav
  Processing: hiphop.00015.wav
  Processing: hiphop.00016.wav
  Processing: hiphop.00017.wav
  Processing: hiphop.00018.wav
  Processing: hiphop.00019.wav
  Processing: hiphop.00020.wav
  Processing: hiphop.00021.wav
  Processing: hiphop.00022.wav
  Processing: hiphop.00023.wav
  Processing: hiphop.00024.wav
  Processing: hiphop.00025.wav
  Processing: hiphop.00026.wav
  Processing: hiphop.00027.wav
  Processing: hiphop.00028.wav
  Processing: hiphop.00029.wav
  Processing: hiphop.00030.wav
  Processing: hiphop.00031.wav
  Skipped (short file)
  Processing: hiphop.00032.wav
  Skipped (short file)
  Processing: hiphop.00033.wav
  Processing: hiphop.00034.wav
  Processing: hiphop.00035.wav
  Processing: hiphop.00036.wav
  Processing: hiphop.00037.wav
  Processing: hiphop.00038.wav
  Processing: hiphop.00039.wav
  Processing: hiphop.00040.wav
  Processing: hiphop.00041.wav
  Processing: hiphop.00042.wav
  Processing: hiphop.00043.wav
  Processing: hiphop.00044.wav
  Processing: hiphop.00045.wav
  Processing: hiphop.00046.wav
  Processing: hiphop.00047.wav
  Processing: hiphop.00048.wav
  Processing: hiphop.00049.wav
  Processing: hiphop.00050.wav
  Processing: hiphop.00051.wav
  Processing: hiphop.00052.wav
  Processing: hiphop.00053.wav
  Processing: hiphop.00054.wav
  Processing: hiphop.00055.wav
  Processing: hiphop.00056.wav
  Processing: hiphop.00057.wav
  Processing: hiphop.00058.wav
  Processing: hiphop.00059.wav
  Processing: hiphop.00060.wav
  Processing: hiphop.00061.wav
  Processing: hiphop.00062.wav
  Processing: hiphop.00063.wav
  Processing: hiphop.00064.wav
  Processing: hiphop.00065.wav
  Processing: hiphop.00066.wav
  Processing: hiphop.00067.wav
  Processing: hiphop.00068.wav
  Processing: hiphop.00069.wav
  Processing: hiphop.00070.wav
  Processing: hiphop.00071.wav
  Processing: hiphop.00072.wav
  Processing: hiphop.00073.wav
  Processing: hiphop.00074.wav
  Processing: hiphop.00075.wav
  Processing: hiphop.00076.wav
  Processing: hiphop.00077.wav
  Processing: hiphop.00078.wav
  Processing: hiphop.00079.wav
  Processing: hiphop.00080.wav
  Processing: hiphop.00081.wav
  Processing: hiphop.00082.wav
  Processing: hiphop.00083.wav
  Processing: hiphop.00084.wav
  Processing: hiphop.00085.wav
  Processing: hiphop.00086.wav
  Processing: hiphop.00087.wav
  Processing: hiphop.00088.wav
  Processing: hiphop.00089.wav
  Processing: hiphop.00090.wav
  Processing: hiphop.00091.wav
  Processing: hiphop.00092.wav
  Processing: hiphop.00093.wav
  Processing: hiphop.00094.wav
  Processing: hiphop.00095.wav
  Processing: hiphop.00096.wav
  Processing: hiphop.00097.wav
  Processing: hiphop.00098.wav
  Processing: hiphop.00099.wav
Processing Genre: jazz
  Processing: jazz.00000.wav
  Processing: jazz.00001.wav
  Processing: jazz.00002.wav
  Processing: jazz.00003.wav
  Processing: jazz.00004.wav
  Processing: jazz.00005.wav
  Processing: jazz.00006.wav
  Processing: jazz.00007.wav
  Processing: jazz.00008.wav
  Processing: jazz.00009.wav
  Processing: jazz.00010.wav
  Processing: jazz.00011.wav
  Processing: jazz.00012.wav
  Processing: jazz.00013.wav
  Processing: jazz.00014.wav
  Processing: jazz.00015.wav
  Processing: jazz.00016.wav
  Processing: jazz.00017.wav
  Processing: jazz.00018.wav
  Processing: jazz.00019.wav
  Processing: jazz.00020.wav
  Processing: jazz.00021.wav
  Processing: jazz.00022.wav
  Processing: jazz.00023.wav
  Processing: jazz.00024.wav
  Processing: jazz.00025.wav
  Processing: jazz.00026.wav
  Processing: jazz.00027.wav
  Processing: jazz.00028.wav
  Processing: jazz.00029.wav
  Processing: jazz.00030.wav
  Processing: jazz.00031.wav
  Processing: jazz.00032.wav
  Processing: jazz.00033.wav
  Processing: jazz.00034.wav
  Processing: jazz.00035.wav
  Processing: jazz.00036.wav
  Processing: jazz.00037.wav
  Processing: jazz.00038.wav
  Processing: jazz.00039.wav
  Processing: jazz.00040.wav
  Processing: jazz.00041.wav
  Processing: jazz.00042.wav
  Processing: jazz.00043.wav
  Processing: jazz.00044.wav
  Processing: jazz.00045.wav
  Processing: jazz.00046.wav
  Processing: jazz.00047.wav
  Processing: jazz.00048.wav
  Processing: jazz.00049.wav
  Processing: jazz.00050.wav
  Processing: jazz.00051.wav
  Processing: jazz.00052.wav
  Processing: jazz.00053.wav
  Processing: jazz.00054.wav
Error processing archive/Data/genres_original\jazz\jazz.00054.wav:
  Processing: jazz.00055.wav

C:\Users\rutvi\AppData\Local\Temp\ipykernel_12760\1594510137.py:83: UserWarning: PySoundFile failed. Trying audioread instead.
  signal, sr = librosa.load(

  Processing: jazz.00056.wav
  Processing: jazz.00057.wav
  Processing: jazz.00058.wav
  Processing: jazz.00059.wav
  Processing: jazz.00060.wav
  Processing: jazz.00061.wav
  Processing: jazz.00062.wav
  Processing: jazz.00063.wav
  Processing: jazz.00064.wav
  Processing: jazz.00065.wav
  Processing: jazz.00066.wav
  Processing: jazz.00067.wav
  Processing: jazz.00068.wav
  Processing: jazz.00069.wav
  Processing: jazz.00070.wav
  Processing: jazz.00071.wav
  Processing: jazz.00072.wav
  Processing: jazz.00073.wav
  Processing: jazz.00074.wav
  Processing: jazz.00075.wav
  Processing: jazz.00076.wav
  Processing: jazz.00077.wav
  Processing: jazz.00078.wav
  Processing: jazz.00079.wav
  Processing: jazz.00080.wav
  Processing: jazz.00081.wav
  Processing: jazz.00082.wav
  Processing: jazz.00083.wav
  Processing: jazz.00084.wav
  Processing: jazz.00085.wav
  Processing: jazz.00086.wav
  Processing: jazz.00087.wav
  Processing: jazz.00088.wav
  Processing: jazz.00089.wav
  Processing: jazz.00090.wav
  Processing: jazz.00091.wav
  Processing: jazz.00092.wav
  Processing: jazz.00093.wav
  Processing: jazz.00094.wav
  Processing: jazz.00095.wav
  Processing: jazz.00096.wav
  Processing: jazz.00097.wav
  Processing: jazz.00098.wav
  Processing: jazz.00099.wav
Processing Genre: metal
  Processing: metal.00000.wav
  Processing: metal.00001.wav
  Processing: metal.00002.wav
  Processing: metal.00003.wav
  Processing: metal.00004.wav
  Processing: metal.00005.wav
  Processing: metal.00006.wav
  Processing: metal.00007.wav
  Processing: metal.00008.wav
  Processing: metal.00009.wav
  Processing: metal.00010.wav
  Processing: metal.00011.wav
  Processing: metal.00012.wav
  Processing: metal.00013.wav
  Processing: metal.00014.wav
  Processing: metal.00015.wav
  Processing: metal.00016.wav
  Processing: metal.00017.wav
  Processing: metal.00018.wav
  Processing: metal.00019.wav
  Processing: metal.00020.wav
  Processing: metal.00021.wav
  Processing: metal.00022.wav
  Processing: metal.00023.wav
  Processing: metal.00024.wav
  Processing: metal.00025.wav
  Processing: metal.00026.wav
  Processing: metal.00027.wav
  Processing: metal.00028.wav
  Processing: metal.00029.wav
  Processing: metal.00030.wav
  Processing: metal.00031.wav
  Processing: metal.00032.wav
  Processing: metal.00033.wav
  Processing: metal.00034.wav
  Processing: metal.00035.wav
  Processing: metal.00036.wav
  Processing: metal.00037.wav
  Processing: metal.00038.wav
  Processing: metal.00039.wav
  Processing: metal.00040.wav
  Processing: metal.00041.wav
  Processing: metal.00042.wav
  Processing: metal.00043.wav
  Processing: metal.00044.wav
  Processing: metal.00045.wav
  Processing: metal.00046.wav
  Processing: metal.00047.wav
  Processing: metal.00048.wav
  Processing: metal.00049.wav
  Processing: metal.00050.wav
  Processing: metal.00051.wav
  Processing: metal.00052.wav
  Processing: metal.00053.wav
  Processing: metal.00054.wav
  Processing: metal.00055.wav
  Processing: metal.00056.wav
  Processing: metal.00057.wav
  Processing: metal.00058.wav
  Processing: metal.00059.wav
  Processing: metal.00060.wav
  Processing: metal.00061.wav
  Processing: metal.00062.wav
  Processing: metal.00063.wav
  Processing: metal.00064.wav
  Processing: metal.00065.wav
  Processing: metal.00066.wav
  Processing: metal.00067.wav
  Processing: metal.00068.wav
  Processing: metal.00069.wav
  Processing: metal.00070.wav
  Processing: metal.00071.wav
  Processing: metal.00072.wav
  Processing: metal.00073.wav
  Processing: metal.00074.wav
  Processing: metal.00075.wav
  Processing: metal.00076.wav
  Processing: metal.00077.wav
  Processing: metal.00078.wav
  Processing: metal.00079.wav
  Processing: metal.00080.wav
  Processing: metal.00081.wav
  Processing: metal.00082.wav
  Processing: metal.00083.wav
  Processing: metal.00084.wav
  Processing: metal.00085.wav
  Processing: metal.00086.wav
  Processing: metal.00087.wav
  Processing: metal.00088.wav
  Processing: metal.00089.wav
  Processing: metal.00090.wav
  Processing: metal.00091.wav
  Processing: metal.00092.wav
  Processing: metal.00093.wav
  Processing: metal.00094.wav
  Processing: metal.00095.wav
  Processing: metal.00096.wav
  Processing: metal.00097.wav
  Processing: metal.00098.wav
  Processing: metal.00099.wav
Processing Genre: pop
  Processing: pop.00000.wav
  Processing: pop.00001.wav
  Processing: pop.00002.wav
  Processing: pop.00003.wav
  Processing: pop.00004.wav
  Processing: pop.00005.wav
  Processing: pop.00006.wav
  Processing: pop.00007.wav
  Processing: pop.00008.wav
  Processing: pop.00009.wav
  Processing: pop.00010.wav
  Processing: pop.00011.wav
  Processing: pop.00012.wav
  Processing: pop.00013.wav
  Processing: pop.00014.wav
  Processing: pop.00015.wav
  Processing: pop.00016.wav
  Processing: pop.00017.wav
  Processing: pop.00018.wav
  Processing: pop.00019.wav
  Processing: pop.00020.wav
  Processing: pop.00021.wav
  Processing: pop.00022.wav
  Processing: pop.00023.wav
  Processing: pop.00024.wav
  Processing: pop.00025.wav
  Processing: pop.00026.wav
  Processing: pop.00027.wav
  Processing: pop.00028.wav
  Processing: pop.00029.wav
  Processing: pop.00030.wav
  Processing: pop.00031.wav
  Processing: pop.00032.wav
  Processing: pop.00033.wav
  Processing: pop.00034.wav
  Processing: pop.00035.wav
  Processing: pop.00036.wav
  Processing: pop.00037.wav
  Processing: pop.00038.wav
  Processing: pop.00039.wav
  Processing: pop.00040.wav
  Processing: pop.00041.wav
  Processing: pop.00042.wav
  Processing: pop.00043.wav
  Processing: pop.00044.wav
  Processing: pop.00045.wav
  Processing: pop.00046.wav
  Processing: pop.00047.wav
  Processing: pop.00048.wav
  Processing: pop.00049.wav
  Processing: pop.00050.wav
  Processing: pop.00051.wav
  Processing: pop.00052.wav
  Processing: pop.00053.wav
  Processing: pop.00054.wav
  Processing: pop.00055.wav
  Processing: pop.00056.wav
  Processing: pop.00057.wav
  Processing: pop.00058.wav
  Processing: pop.00059.wav
  Processing: pop.00060.wav
  Processing: pop.00061.wav
  Processing: pop.00062.wav
  Processing: pop.00063.wav
  Processing: pop.00064.wav
  Processing: pop.00065.wav
  Processing: pop.00066.wav
  Processing: pop.00067.wav
  Processing: pop.00068.wav
  Processing: pop.00069.wav
  Processing: pop.00070.wav
  Processing: pop.00071.wav
  Processing: pop.00072.wav
  Processing: pop.00073.wav
  Processing: pop.00074.wav
  Processing: pop.00075.wav
  Processing: pop.00076.wav
  Processing: pop.00077.wav
  Processing: pop.00078.wav
  Processing: pop.00079.wav
  Processing: pop.00080.wav
  Processing: pop.00081.wav
  Processing: pop.00082.wav
  Processing: pop.00083.wav
  Processing: pop.00084.wav
  Processing: pop.00085.wav
  Processing: pop.00086.wav
  Processing: pop.00087.wav
  Processing: pop.00088.wav
  Processing: pop.00089.wav
  Processing: pop.00090.wav
  Processing: pop.00091.wav
  Processing: pop.00092.wav
  Processing: pop.00093.wav
  Processing: pop.00094.wav
  Processing: pop.00095.wav
  Processing: pop.00096.wav
  Processing: pop.00097.wav
  Processing: pop.00098.wav
  Processing: pop.00099.wav
Processing Genre: reggae
  Processing: reggae.00000.wav
  Processing: reggae.00001.wav
  Processing: reggae.00002.wav
  Processing: reggae.00003.wav
  Processing: reggae.00004.wav
  Processing: reggae.00005.wav
  Processing: reggae.00006.wav
  Processing: reggae.00007.wav
  Processing: reggae.00008.wav
  Processing: reggae.00009.wav
  Processing: reggae.00010.wav
  Processing: reggae.00011.wav
  Processing: reggae.00012.wav
  Processing: reggae.00013.wav
  Processing: reggae.00014.wav
  Processing: reggae.00015.wav
  Processing: reggae.00016.wav
  Processing: reggae.00017.wav
  Processing: reggae.00018.wav
  Processing: reggae.00019.wav
  Processing: reggae.00020.wav
  Processing: reggae.00021.wav
  Processing: reggae.00022.wav
  Processing: reggae.00023.wav
  Processing: reggae.00024.wav
  Processing: reggae.00025.wav
  Processing: reggae.00026.wav
  Processing: reggae.00027.wav
  Processing: reggae.00028.wav
  Processing: reggae.00029.wav
  Processing: reggae.00030.wav
  Processing: reggae.00031.wav
  Processing: reggae.00032.wav
  Processing: reggae.00033.wav
  Processing: reggae.00034.wav
  Processing: reggae.00035.wav
  Processing: reggae.00036.wav
  Processing: reggae.00037.wav
  Processing: reggae.00038.wav
  Processing: reggae.00039.wav
  Processing: reggae.00040.wav
  Processing: reggae.00041.wav
  Processing: reggae.00042.wav
  Processing: reggae.00043.wav
  Processing: reggae.00044.wav
  Processing: reggae.00045.wav
  Processing: reggae.00046.wav
  Processing: reggae.00047.wav
  Processing: reggae.00048.wav
  Processing: reggae.00049.wav
  Processing: reggae.00050.wav
  Processing: reggae.00051.wav
  Processing: reggae.00052.wav
  Processing: reggae.00053.wav
  Processing: reggae.00054.wav
  Processing: reggae.00055.wav
  Processing: reggae.00056.wav
  Processing: reggae.00057.wav
  Processing: reggae.00058.wav
  Processing: reggae.00059.wav
  Processing: reggae.00060.wav
  Processing: reggae.00061.wav
  Processing: reggae.00062.wav
  Processing: reggae.00063.wav
  Processing: reggae.00064.wav
  Processing: reggae.00065.wav
  Processing: reggae.00066.wav
  Processing: reggae.00067.wav
  Processing: reggae.00068.wav
  Processing: reggae.00069.wav
  Processing: reggae.00070.wav
  Processing: reggae.00071.wav
  Processing: reggae.00072.wav
  Processing: reggae.00073.wav
  Processing: reggae.00074.wav
  Processing: reggae.00075.wav
  Processing: reggae.00076.wav
  Processing: reggae.00077.wav
  Processing: reggae.00078.wav
  Processing: reggae.00079.wav
  Processing: reggae.00080.wav
  Processing: reggae.00081.wav
  Processing: reggae.00082.wav
  Processing: reggae.00083.wav
  Processing: reggae.00084.wav
  Processing: reggae.00085.wav
  Processing: reggae.00086.wav
  Processing: reggae.00087.wav
  Processing: reggae.00088.wav
  Processing: reggae.00089.wav
  Processing: reggae.00090.wav
  Processing: reggae.00091.wav
  Processing: reggae.00092.wav
  Processing: reggae.00093.wav
  Processing: reggae.00094.wav
  Processing: reggae.00095.wav
  Processing: reggae.00096.wav
  Processing: reggae.00097.wav
  Processing: reggae.00098.wav
  Processing: reggae.00099.wav
Processing Genre: rock
  Processing: rock.00000.wav
  Processing: rock.00001.wav
  Processing: rock.00002.wav
  Processing: rock.00003.wav
  Processing: rock.00004.wav
  Processing: rock.00005.wav
  Processing: rock.00006.wav
  Processing: rock.00007.wav
  Processing: rock.00008.wav
  Processing: rock.00009.wav
  Processing: rock.00010.wav
  Processing: rock.00011.wav
  Processing: rock.00012.wav
  Processing: rock.00013.wav
  Processing: rock.00014.wav
  Processing: rock.00015.wav
  Processing: rock.00016.wav
  Processing: rock.00017.wav
  Processing: rock.00018.wav
  Processing: rock.00019.wav
  Processing: rock.00020.wav
  Processing: rock.00021.wav
  Processing: rock.00022.wav
  Processing: rock.00023.wav
  Processing: rock.00024.wav
  Processing: rock.00025.wav
  Processing: rock.00026.wav
  Processing: rock.00027.wav
  Processing: rock.00028.wav
  Processing: rock.00029.wav
  Processing: rock.00030.wav
  Processing: rock.00031.wav
  Processing: rock.00032.wav
  Processing: rock.00033.wav
  Processing: rock.00034.wav
  Processing: rock.00035.wav
  Processing: rock.00036.wav
  Processing: rock.00037.wav
  Processing: rock.00038.wav
  Skipped (short file)
  Processing: rock.00039.wav
  Processing: rock.00040.wav
  Processing: rock.00041.wav
  Processing: rock.00042.wav
  Processing: rock.00043.wav
  Processing: rock.00044.wav
  Processing: rock.00045.wav
  Processing: rock.00046.wav
  Processing: rock.00047.wav
  Processing: rock.00048.wav
  Processing: rock.00049.wav
  Processing: rock.00050.wav
  Processing: rock.00051.wav
  Processing: rock.00052.wav
  Processing: rock.00053.wav
  Processing: rock.00054.wav
  Processing: rock.00055.wav
  Processing: rock.00056.wav
  Processing: rock.00057.wav
  Processing: rock.00058.wav
  Processing: rock.00059.wav
  Processing: rock.00060.wav
  Processing: rock.00061.wav
  Processing: rock.00062.wav
  Processing: rock.00063.wav
  Processing: rock.00064.wav
  Processing: rock.00065.wav
  Processing: rock.00066.wav
  Processing: rock.00067.wav
  Processing: rock.00068.wav
  Processing: rock.00069.wav
  Processing: rock.00070.wav
  Processing: rock.00071.wav
  Processing: rock.00072.wav
  Processing: rock.00073.wav
  Processing: rock.00074.wav
  Processing: rock.00075.wav
  Processing: rock.00076.wav
  Processing: rock.00077.wav
  Processing: rock.00078.wav
  Processing: rock.00079.wav
  Processing: rock.00080.wav
  Processing: rock.00081.wav
  Processing: rock.00082.wav
  Processing: rock.00083.wav
  Processing: rock.00084.wav
  Processing: rock.00085.wav
  Processing: rock.00086.wav
  Processing: rock.00087.wav
  Processing: rock.00088.wav
  Processing: rock.00089.wav
  Processing: rock.00090.wav
  Processing: rock.00091.wav
  Processing: rock.00092.wav
  Processing: rock.00093.wav
  Processing: rock.00094.wav
  Processing: rock.00095.wav
  Processing: rock.00096.wav
  Processing: rock.00097.wav
  Processing: rock.00098.wav
  Processing: rock.00099.wav
Feature Extraction Completed
Total Feature Vectors: 9900
Total Labels: 9900
Feature Vector Size: 28

In [30]:
import json
import pandas as pd

with open("data.json", "r") as f:
    data = json.load(f)

In [31]:
data.keys()

dict_keys(['mapping', 'labels', 'features'])

In [32]:
features_df = pd.DataFrame(data["features"])

In [33]:
features_df.head()

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,27
0,-119.018044,125.080353,-23.394335,41.321732,-5.931896,20.092751,-16.031523,17.811024,-14.643774,10.218312,...,0.294086,0.271127,0.300573,0.250038,0.337069,0.347898,0.344555,1773.358004,3714.063439,0.081851
1,-125.977150,122.374191,-20.679750,50.035042,-11.250690,21.386393,-15.864703,19.418631,-12.440535,17.862537,...,0.382698,0.483460,0.499978,0.294814,0.262002,0.339586,0.370314,1817.244034,3870.510442,0.087173
2,-132.618149,114.815521,-14.718568,50.017944,-0.424878,24.517357,-13.401937,15.444255,-13.006782,10.309508,...,0.202625,0.227462,0.379300,0.314705,0.359410,0.494625,0.369133,1790.722358,4000.206581,0.071383
3,-118.325325,131.587173,-18.493637,39.478863,-12.992121,20.173027,-14.325366,18.541624,-13.470632,12.837085,...,0.460557,0.362261,0.389526,0.276905,0.286163,0.423766,0.421856,1660.545231,3579.149639,0.069426
4,-106.182106,134.275955,-19.761967,39.920498,-14.074066,18.501814,-15.400158,19.148363,-17.971155,14.170511,...,0.341947,0.327873,0.443653,0.275517,0.274796,0.495465,0.365276,1634.465076,3480.096905,0.070102

In [34]:
features_df["genre_label"] = data["labels"]

In [35]:
features_df.head()

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,genre_label
0,-119.018044,125.080353,-23.394335,41.321732,-5.931896,20.092751,-16.031523,17.811024,-14.643774,10.218312,...,0.271127,0.300573,0.250038,0.337069,0.347898,0.344555,1773.358004,3714.063439,0.081851,0
1,-125.977150,122.374191,-20.679750,50.035042,-11.250690,21.386393,-15.864703,19.418631,-12.440535,17.862537,...,0.483460,0.499978,0.294814,0.262002,0.339586,0.370314,1817.244034,3870.510442,0.087173,0
2,-132.618149,114.815521,-14.718568,50.017944,-0.424878,24.517357,-13.401937,15.444255,-13.006782,10.309508,...,0.227462,0.379300,0.314705,0.359410,0.494625,0.369133,1790.722358,4000.206581,0.071383,0
3,-118.325325,131.587173,-18.493637,39.478863,-12.992121,20.173027,-14.325366,18.541624,-13.470632,12.837085,...,0.362261,0.389526,0.276905,0.286163,0.423766,0.421856,1660.545231,3579.149639,0.069426,0
4,-106.182106,134.275955,-19.761967,39.920498,-14.074066,18.501814,-15.400158,19.148363,-17.971155,14.170511,...,0.327873,0.443653,0.275517,0.274796,0.495465,0.365276,1634.465076,3480.096905,0.070102,0

In [36]:
features_df.shape

(9900, 29)

In [37]:
features_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9900 entries, 0 to 9899
Data columns (total 29 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   0            9900 non-null   float64
 1   1            9900 non-null   float64
 2   2            9900 non-null   float64
 3   3            9900 non-null   float64
 4   4            9900 non-null   float64
 5   5            9900 non-null   float64
 6   6            9900 non-null   float64
 7   7            9900 non-null   float64
 8   8            9900 non-null   float64
 9   9            9900 non-null   float64
 10  10           9900 non-null   float64
 11  11           9900 non-null   float64
 12  12           9900 non-null   float64
 13  13           9900 non-null   float64
 14  14           9900 non-null   float64
 15  15           9900 non-null   float64
 16  16           9900 non-null   float64
 17  17           9900 non-null   float64
 18  18           9900 non-null   float64
 19  19           9900 non-null   float64
 20  20           9900 non-null   float64
 21  21           9900 non-null   float64
 22  22           9900 non-null   float64
 23  23           9900 non-null   float64
 24  24           9900 non-null   float64
 25  25           9900 non-null   float64
 26  26           9900 non-null   float64
 27  27           9900 non-null   float64
 28  genre_label  9900 non-null   int64
dtypes: float64(28), int64(1)
memory usage: 2.2 MB

In [38]:
features_df.to_csv(
    "features.csv",
    index=False
)

In [39]:
import os

os.path.exists("features.csv")

True

In [40]:
import pandas as pd

df = pd.read_csv("features.csv")

df.head()

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,genre_label
0,-119.018044,125.080353,-23.394335,41.321732,-5.931896,20.092751,-16.031523,17.811024,-14.643774,10.218312,...,0.271127,0.300573,0.250038,0.337069,0.347898,0.344555,1773.358004,3714.063439,0.081851,0
1,-125.977150,122.374191,-20.679750,50.035042,-11.250690,21.386393,-15.864703,19.418631,-12.440535,17.862537,...,0.483460,0.499978,0.294814,0.262002,0.339586,0.370314,1817.244034,3870.510442,0.087173,0
2,-132.618149,114.815521,-14.718568,50.017944,-0.424878,24.517357,-13.401937,15.444255,-13.006782,10.309508,...,0.227462,0.379300,0.314705,0.359410,0.494625,0.369133,1790.722358,4000.206581,0.071383,0
3,-118.325325,131.587173,-18.493637,39.478863,-12.992121,20.173027,-14.325366,18.541624,-13.470632,12.837085,...,0.362261,0.389526,0.276905,0.286163,0.423766,0.421856,1660.545231,3579.149639,0.069426,0
4,-106.182106,134.275955,-19.761967,39.920498,-14.074066,18.501814,-15.400158,19.148363,-17.971155,14.170511,...,0.327873,0.443653,0.275517,0.274796,0.495465,0.365276,1634.465076,3480.096905,0.070102,0

In [41]:
df.shape

(9900, 29)

In [42]:
import pandas as pd

In [43]:
CSV_PATH = "features.csv"

In [44]:
features_df = pd.DataFrame(data["features"])

features_df["genre_label"] = data["labels"]

In [45]:
features_df.to_csv(
    CSV_PATH,
    index=False
)